PRODUCT_VERSION_MAJOR = 0
PRODUCT_VERSION_MINOR = 1

ifeq ($(CELESTIAL_VERSION_APPEND_TIME_OF_DAY),true)
    CELESTIAL_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    CELESTIAL_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set CELESTIAL_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef
    ifdef RELEASE_TYPE
        # Starting with "CELESTIAL_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^CELESTIAL_||g')
        CELESTIAL_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(CELESTIAL_BUILDTYPE)),)
    CELESTIAL_BUILDTYPE := UNOFFICIAL
    CELESTIAL_EXTRAVERSION :=
endif

ifeq ($(CELESTIAL_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        CELESTIAL_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

CELESTIAL_VERSION_SUFFIX := $(CELESTIAL_BUILD_DATE)-$(CELESTIAL_BUILDTYPE)$(CELESTIAL_EXTRAVERSION)-$(CELESTIAL_BUILD)

# Internal version
CELESTIAL_VERSION := CELESTIAL_$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CELESTIAL_VERSION_SUFFIX)

# Display version
CELESTIAL_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(CELESTIAL_VERSION_SUFFIX)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
 ro.celestial.version=$(CELESTIAL_VERSION) \
 ro.celestial.releasetype=$(CELESTIAL_BUILDTYPE) \
 ro.mod.version=$(CELESTIAL_VERSION) \
 ro.celestial.build.version=$(CELESTIAL_DISPLAY_VERSION) \
 ro.celestial.settings.android_version=$(CELESTIAL_EXTRAVERSION)

ROM_FINGERPRINT := CelestialDroid/$(CELESTIAL_VERSION)/$(TARGET_PRODUCT_SHORT)/$(shell date -u +%Y%m%d-%H%M)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
 ro.celestial.display.version=$(CELESTIAL_DISPLAY_VERSION) \
 ro.celestial.fingerprint=$(ROM_FINGERPRINT)
